import { json } from '@sveltejs/kit';
import RatingDAO from '$lib/DAOClasses/RatingDAO.js'; // Adjust as necessary
import Rating from '$lib/Classes/Rating.js';

/**
 * @swagger
 * /API/ratings:
 *   post:
 *     summary: Add a new rating
 *     tags: [Ratings]
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               ratingData:
 *                 type: object
 *                 properties:
 *                   rate:
 *                     type: integer
 *                     description: The rating value
 *                   fileID:
 *                     type: string
 *                     description: The ID of the file being rated
 *     responses:
 *       201:
 *         description: Rating added successfully
 *       500:
 *         description: Failed to add rating
 */
export async function POST({ request }) {
    const { ratingData } = await request.json();
    const ratingDAO = new RatingDAO();

    try {
        await ratingDAO.connect();
        const rating = new Rating(null, ratingData.rate, ratingData.fileID); // Assuming ratingID is generated by the database
        const success = await ratingDAO.addRating(rating);

        if (success) {
            return json({ message: 'Rating added successfully' }, { status: 201 });
        } else {
            return json({ error: 'Failed to add rating' }, { status: 500 });
        }
    } catch (error) {
        console.error('Error adding rating:', error);
        return json({ error: 'Internal Server Error' }, { status: 500 });
    } finally {
        await ratingDAO.disconnect();
    }
}
